# This rule is not used by the project wso2is-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to wso2.it.auth.gr resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wso2is-operator
    app.kubernetes.io/managed-by: kustomize
  name: wso2isinstance-viewer-role
rules:
- apiGroups:
  - wso2.it.auth.gr
  resources:
  - wso2isinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wso2.it.auth.gr
  resources:
  - wso2isinstances/status
  verbs:
  - get
